'use strict'

exports.StateRestock = {
    ISSUED : "ISSUED",
    DELIVERY : "DELIVERY",
    DELIVERED : "DELIVERED",
    TESTED : "TESTED",
    COMPLETEDRETURN : "COMPLETEDRETURN",
    COMPLETED : "COMPLETED"
}

exports.StateInternal = {
    ISSUED : "ISSUED",
    ACCEPTED : "ACCEPTED",
    REFUSED : "REFUSED",
    CANCELED : "CANCELED",
    COMPLETED : "COMPLETED"
}